---
abstract: 'Lets you write DBIC add_column() definitions as attribute options (DEPRECATED)'
author:
  - 'Norbert Buchmuller, C<< <norbi at nix.hu> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.93'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-DBIC-AddColumn
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  DBIx::Class::MooseColumns: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/mendel/DBIx-Class-MooseColumns.git
version: 0.05
